fixup! lower perf even paranoid level

diff --git a/.github/workflows/swift_test_matrix.yml b/.github/workflows/swift_test_matrix.yml
--- a/.github/workflows/swift_test_matrix.yml
+++ b/.github/workflows/swift_test_matrix.yml
@@ -39,7 +39,7 @@ jobs:
         if: ${{ matrix.config.platform != 'Windows' }}
         run: |
           echo "Current perf_event_paranoid: $(cat /proc/sys/kernel/perf_event_paranoid)"
-          sysctl -w kernel.perf_event_paranoid=-1 || echo "Failed to set perf_event_paranoid (expected in some environments)"
+          sudo sysctl -w kernel.perf_event_paranoid=-1 || echo "Failed to set perf_event_paranoid (expected in some environments)"
           echo "New perf_event_paranoid: $(cat /proc/sys/kernel/perf_event_paranoid)"
       - name: Run matrix job
         if: ${{ matrix.config.platform != 'Windows' }}
